name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install storybook dependencies
        run: cd packages/storybook && npm install --no-workspaces
      
      - name: Build Storybook
        run: cd packages/storybook && npm run build-storybook
      
      - name: Echo release info
        run: echo "Release workflow completed successfully" 